### PR TITLE
additional notebook.

### PR DESCRIPTION
**Pull request by miguelcleon**
I could also do this second demo if there is time. 

I tried adding the ui_utils into the code folder but I'm not able to import. It is commented out here: 
https://github.com/BiG-CZ/wshp2017_tutorial_content/compare/master...miguelcleon:master?expand=1#diff-2f207230c34a63ce64f450c0f31b1228R21

### CODE REVIEW

**Comment by emiliom** [comment]
Thanks for the offer, @miguelcleon. The part I like from your notebook is the insertion of a new variable per se, the last two cells (but mostly cell 10) and the explanatory text before cell 10. The rest is largely duplicative of [your other example notebook](https://github.com/BiG-CZ/wshp2017_tutorial_content/blob/master/notebooks/ODM2PythonAPI_for_ODM2_Admin_example4.ipynb) and doesn't add anything new in my opinion -- and that's a bunch of code to not demo any significantly new aspect :stuck_out_tongue_winking_eye:. 

I think that kernel of new stuff may be better suited as an add-on to another notebook, such as Example 3 or something else that @horsburgh may be putting together to demo `odm2api`. So, I'll leave the PR unmerged for @horsburgh to think about and borrow liberally.

As for using your `ui_utils` code, how about using `sys.path.insert()` to add the `code` folder path? See ODM2 Examples 1-3 for examples of the path extraction and concatenation used to point to the `data` folder (which is at the same hierarchy level as `code`), as an example; that generic code will make the path reference work on both JupyterHub and a local install. But, two more comments about this module:
- If you're going to use it in a notebook that will go on the repo, please rename it to something less generic in this broader context (eg, odm2admin_ui_utils, miguel_ui_utils, etc)
- You import bokeh. bokeh is not on our conda env file. It would need to be added, and Don would have to deploy it on JupyterHub (that's a manual step). He could do that, but I'd first like to have some confidence that it will actually be used.

Thanks!

**Comment by horsburgh** [comment]
I wasn’t planning on developing new content for the ODM2 Python API discussion.

**Comment by miguelcleon** [comment]
Ok, I can successfully import the now named mcl_ui_utils, I removed bokeh. I removed the listing of CVVariableName. @emiliom I think this addresses your comments.

**Comment by emiliom** [comment]
@miguelcleon I'm not clear about the full extent of changes in this new commit. It'll be easier if you tell me in person in a bit.

**Pull request merged**
